Repository pachyderm/pachyderm, pull requests merged in 2019-10, with the labels that each got.

#4152 Added support for importing kubernetes contexts
  src/client/pkg/config/config.pb.go
  src/client/pkg/config/config.proto
  src/client/pkg/config/kube_config.go
  src/server/config/cmds.go
  src/server/pkg/deploy/cmds/cmds.go
Labels: needs docs

#4034 [WIP][DOC][3915] Add Getting Started with PacHub.
  doc/_images/s_list_of_buckets.png
  doc/conf.py
  doc/deployment/index.rst
  doc/getting_started/beginner_tutorial.rst
  doc/images/d_pachub_steps.svg
  doc/images/plus.svg
  doc/images/s_list_of_buckets.png
  doc/images/s_load_data.png
  doc/images/s_load_data_result.png
  doc/images/s_pachub_cluster.png
  doc/images/s_pachub_ready.png
  doc/images/s_pipeline_created.png
  doc/index.rst
  doc/pachub/pachub_getting_started.md
  doc/pachub/pachub_opencv.md
  doc/tutorials/index.rst
  doc/tutorials/screencast-opencv.md
Labels: docs

#4191 Fix instructions to reflect latest changes
  doc/images/s_pachub_cluster.png
  doc/pachub/pachub_getting_started.md
Labels: docs

#4198 Add a note about the Docker runtime
  doc/deployment/index.rst
  doc/getting_started/local_installation.md
Labels: docs

#4197 [DOC] Deploy with tls
  doc/deployment/deploy_w_tls.md
  doc/deployment/index.rst
Labels: docs

#4122 [DOC] Added Joins
  doc/concepts/pipeline-concepts/index.rst
  doc/concepts/pipeline-concepts/pipeline/index.rst
  doc/concepts/pipeline-concepts/pipeline/join.md
  doc/reference/pipeline_spec.md
  examples/joins/Dockerfile
  examples/joins/Makefile
  examples/joins/README.md
  examples/joins/joins.json
  examples/joins/joins.py
Labels: docs

#4202 [DOC] Add import k8s context
  doc/deployment/import-kubernetes-context.md
  doc/deployment/index.rst
Labels: docs

#4230 Fix a typo in the Spout example specification
  doc/concepts/pipeline-concepts/pipeline/spout.md
Labels: docs

#4246 Landing pages for how-tos, getting started and concepts
  doc/docs/assets/stylesheets/extra.css
  doc/docs/concepts/index.md
  doc/docs/concepts/index.rst
  doc/docs/getting_started/beginner_tutorial.rst
  doc/docs/getting_started/index.md
  doc/docs/getting_started/index.rst
  doc/docs/how-tos/index.md
  doc/docs/how-tos/index.rst
  doc/docs/how-tos/splitting-data/index.md
  doc/mkdocs.yml
Labels: docs

#4263 Closes #4127
  doc/docs/archive/combining.md
  doc/docs/concepts/pipeline-concepts/datum/cross-union.md
  doc/docs/concepts/pipeline-concepts/pipeline/index.md
  doc/docs/concepts/pipeline-concepts/pipeline/join.md
  doc/docs/getting_started/beginner_tutorial.md
  doc/mkdocs.yml
Labels: docs

#4251 [DOC] Add env variables
  doc/docs/deploy-manage/deploy/environment-variables.md
  doc/mkdocs.yml
Labels: docs

#4257 Add robots txt
  doc/conf.py
  doc/custom_theme/layout.html
  doc/robots.txt
Labels: docs

#4229 [DOC]Add a banner
  doc/custom_theme/banner.html
  doc/custom_theme/layout.html
Labels: do-not-merge, docs

#4272 Add a custom 404
  doc/material/404.html
Labels: docs

#4276 add a redirect for .io
  netlify.toml
Labels: docs

#4278 redirects
  netlify.toml
Labels: docs

#4280 deploy with TLS docs fixup
  doc/docs/deploy-manage/deploy/deploy_w_tls.md
  doc/mkdocs.yml
  doc/robots.txt
Labels: docs

#4281 redirects
  netlify.toml
Labels: docs

#4283 Fix a typo
  doc/docs/enterprise/stats.md
Labels: docs

#4282 Fix 404
  doc/material/404.html
Labels: docs

#4288 cherrypick changes and update the pachub docs
  doc/docs/pachub/pachub_getting_started.md
Labels: docs
