Repository pachyderm/pachyderm, pull requests merged in 2019-12, with the labels that each got.

#4367 [DOC]Clarify transaction conflicts
  doc/docs/master/how-tos/use-transactions-to-run-multiple-commands.md
Labels: 1.9.9, docs

#4359 [DOC] Update the pipeline name desc
  doc/docs/master/reference/pipeline_spec.md
Labels: 1.9.9, docs

#4372 Update the path to pachctl docs
  src/server/cmd/pachctl-doc/main.go
Labels: 1.9.9, docs

#4368 CLI pretty printer improvements.
  src/server/pfs/pretty/pretty.go
  src/server/pkg/pretty/pretty.go
  src/server/pps/pretty/pretty.go
  src/server/pps/server/api_server.go
Labels: 1.9.9, needs docs

#4374 [DOC]Add a description field to examples
  doc/docs/master/getting_started/beginner_tutorial.md
  examples/db/query.json
  examples/err_cmd/README.md
  examples/gatk/joint-call.json
  examples/gatk/likelihoods.json
  examples/joins/joins.json
  examples/ml/gpt-2/generate.json
  examples/ml/gpt-2/train.json
  examples/ml/gpt-2/tweets.json
  examples/ml/hyperparameter/model.json
  examples/ml/hyperparameter/select.json
  examples/ml/hyperparameter/split.json
  examples/ml/hyperparameter/test.json
  examples/ml/iris/julia_infer.json
  examples/ml/iris/julia_train.json
  examples/ml/iris/python_infer.json
  examples/ml/iris/python_train.json
  examples/ml/iris/rstats_infer.json
  examples/ml/iris/rstats_train.json
  examples/ml/neon/infer.json
  examples/ml/neon/train.json
  examples/ml/object-detection/detect.json
  examples/ml/object-detection/model.json
  examples/ml/rnn/pipeline-combined.json
  examples/ml/rnn/pipeline-generate.json
  examples/ml/rnn/pipeline-train.json
  examples/ml/tensorflow/pre-processing_and_generation.json
  examples/ml/tensorflow/training_and_export.json
  examples/ml/tensorflow/training_and_export_gpu.json
  examples/opencv/edges.json
  examples/opencv/montage.json
  examples/shuffle/shuffle.json
  examples/spark/pi/estimate_pi_pipeline.json
  examples/spouts/EmailSentimentAnalyzer/imap_spout.json
  examples/spouts/EmailSentimentAnalyzer/sentimentalist.json
  examples/spouts/SQS-S3/sqs-spout.json
  examples/spouts/go-kafka-spout/pipelines/kafka_spout.json
  examples/spouts/go-kafka-spout/pipelines/kafka_spout.pipeline
  examples/transactions/model.json
  examples/word_count/map.json
  examples/word_count/reduce.json
  examples/word_count/scraper.json
Labels: 1.9.9, docs

#4224 Spout markers
  src/server/pachyderm_test.go
  src/server/pfs/server/driver.go
  src/server/pkg/sync/sync.go
  src/server/pps/server/api_server.go
  src/server/worker/api_server.go
  src/server/worker/master.go
Labels: 1.9.9, needs docs

#4389 [DOC]Update 1.9.x config file
  doc/mkdocs-1.9.x.yml
Labels: 1.9.9, docs

#4383 Add transactions to the overview page
  doc/docs/master/how-tos/index.md
  doc/docs/master/how-tos/use-transactions-to-run-multiple-commands.md
Labels: docs

#4381 [DOC]Fix broken docs links and update the examples overview page
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CHANGELOG.md
  CONTRIBUTING.md
  doc/docs/archive/existing_vpc.md
  doc/docs/archive/incrementality.md
  doc/docs/master/contributing/docs-style-guide.md
  doc/docs/master/contributing/setup.md
  doc/docs/master/deploy-manage/deploy/google_cloud_platform.md
  doc/docs/master/enterprise/stats.md
  doc/docs/master/examples/examples.md
  examples/db/README.md
  examples/gatk/README.md
  examples/kubeflow/mnist_with_tfjob/README.md
  examples/kubeflow/mnist_with_tfjob/gcp-kubeflow-pachyderm-setup.sh
  examples/kubeflow/tfjob/README.md
  examples/ml/hyperparameter/README.md
  examples/ml/iris/README.md
  examples/ml/neon/README.md
  examples/ml/object-detection/README.md
  examples/ml/tensorflow/README.md
  examples/run/README.md
  examples/shuffle/README.md
  examples/spark/pi/README.md
  examples/spouts/README.md
  examples/word_count/README.md
Labels: docs

#4394 [DOC] Added a note that stats cannot be disabled after being enabled.
  doc/docs/master/reference/pipeline_spec.md
Labels: docs

#4398 [DOC] Fix a command in the scraper README
  examples/scraper/README.md
Labels: 1.10, docs

#4418 [DOC] Add WSL instructions
  doc/docs/master/getting_started/local_installation.md
  doc/docs/master/getting_started/wsl-deploy.md
  doc/docs/master/how-tos/export-data-out-pachyderm.md
  doc/docs/master/how-tos/load-data-into-pachyderm.md
  doc/mkdocs-master.yml
Labels: 1.10, docs

#4431 s3 gateway API docs updates
  doc/docs/master/reference/s3gateway_api.md
Labels: docs

#4390 [DOC] Minor updates to the EmailSentimentAnalyzer example
  examples/spouts/EmailSentimentAnalyzer/README.md
  examples/spouts/EmailSentimentAnalyzer/imap_spout.json
  examples/spouts/EmailSentimentAnalyzer/imap_spout.py
Labels: 1.9.10

#4435 added max-txn-ops troubleshooting
  doc/docs/1.9.x/troubleshooting/general_troubleshooting.md
  doc/docs/1.9.x/troubleshooting/pipeline_troubleshooting.md
  doc/docs/master/troubleshooting/pipeline_troubleshooting.md
Labels: docs

#4416 Fix bad context connect
  etc/fetch_release_pachctl.py
  etc/reset.py
  go.mod
  go.sum
  src/client/client.go
  src/client/portforwarder.go
  src/plugin/vault/etc/pach-auth.sh
  src/server/cmd/pachctl/cmd/cmd.go
Labels: 1.9.10

#4443 Fix some unfinished commit blocking issues
  src/server/pachyderm_test.go
  src/server/worker/master.go
Labels: 1.9.10

#4436 [DOC]update build/doc
  etc/build/doc
  go.mod
  go.sum
Labels: 1.9.10, docs

#4420 Add test framework for local PFS, fix hashtree leak
  .vscode/tasks.json
  Makefile
  etc/testing/pfs_server.sh
  etc/testing/travis.sh
  go.mod
  go.sum
  src/server/auth/server/api_server.go
  src/server/auth/server/config.go
  src/server/auth/server/saml.go
  src/server/auth/server/testing/admin_test.go
  src/server/auth/server/testing/auth_test.go
  src/server/auth/server/testing/config_test.go
  src/server/auth/server/testing/saml_test.go
  src/server/pfs/cmds/cmds.go
  src/server/pfs/cmds/mount_unix.go
  src/server/pfs/server/block_api_server_test.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/obj_block_api_server.go
  src/server/pfs/server/server_test.go
  src/server/pfs/server/testing.go
  src/server/pfs/server/testing/block_api_server_test.go
  src/server/pfs/server/testing/server_test.go
  src/server/pkg/hashtree/cache.go
  src/server/pkg/hashtree/db.go
  src/server/pkg/hashtree/hashtree_test.go
  src/server/pkg/obj/local_client.go
  src/server/pkg/sync/pipe_windows.go
  src/server/pkg/testutil/env.go
  src/server/pkg/testutil/mock_pachd.go
  src/server/pkg/transactionenv/testing.go
  src/server/transaction/server/server_test.go
  src/server/transaction/server/testing/server_test.go
  src/server/worker/api_server.go
  src/server/worker/api_server_unix.go
  src/server/worker/api_server_windows.go
Labels: 1.9.10

#4447 Add additional logging to pachd setup
  src/server/cmd/pachd/main.go
  src/server/pkg/serviceenv/service_env.go
Labels: 1.9.10

#4419 Run cron
  .vscode/settings.json
  src/client/pps.go
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pachyderm_test.go
  src/server/pkg/testutil/mock_pachd.go
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
  vendor/gopkg.in/src-d/go-billy.v4/go.sum
Labels: 1.9.10, needs docs

#4441 make join datum iterator fast
  go.mod
  go.sum
  src/server/worker/datum_iterator.go
  src/server/worker/datum_iterator_test.go
  src/server/worker/master.go
Labels: 1.9.10
