Repository pachyderm/pachyderm, pull requests merged in 2020-08, with the labels that each got.

#5162 Get enterprise key from stdin
  etc/reset.py
  etc/testing/test_tls.sh
  go.mod
  go.sum
  src/plugin/vault/etc/pach-auth.sh
  src/plugin/vault/etc/test-vault.sh
  src/server/auth/cmds/cmds_test.go
  src/server/enterprise/cmds/cmds.go
  src/server/pkg/cmdutil/password.go
  src/server/pps/cmds/cmds.go
Labels: 1.12, 1.12.0

#5158 Compatibility matrix for IDE
  Makefile
  doc/release_instructions.md
  etc/build/compatibility.sh
  etc/build/dash_compatibility.sh
  etc/build/get_dash_version.go
  etc/build/get_default_version.go
  etc/compatibility/ide/1.12.0
  etc/compatibility/jupyterhub/1.12.0
  etc/compatibility/readme.md
  src/server/pkg/deploy/cmds/cmds.go
  src/server/pkg/deploy/cmds/cmds_test.go
Labels: 1.12, 1.12.0

#5167 Use Pachyderm IDE v1.1.0
  etc/compatibility/ide/1.12.0
  etc/compatibility/jupyterhub/1.12.0
  src/server/pkg/deploy/cmds/cmds.go
Labels: 1.12, 1.12.0

#5171 Fix IDE release notes
  go.mod
  go.sum
  src/server/pkg/deploy/cmds/cmds.go
Labels: 1.12, 1.12.0

#5197 [1.11] Fix python build pipelines when there are no dependencies
  etc/pipeline-build/python/run.sh
  etc/testing/pipeline-build/python_no_deps/main.py
  src/server/pps/cmds/cmds_test.go
Labels: 1.11.2

#5190 Fix BREAK error when listing commits with a limit
  .vscode/tasks.json
  etc/compile/vscode_compile_task.sh
  src/server/pfs/server/driver.go
  src/server/pfs/server/testing/server_test.go
  src/server/pkg/cmdutil/password.go
Labels: 1.11.2, bug

#5191 Make user and master flags for worker log statements mutually exclusive
  src/server/worker/logs/logger.go
Labels: 1.11.2, bug

#5193 CreateRepo with update=True no longer resets repo ACL
  src/server/auth/server/testing/auth_test.go
  src/server/pfs/server/driver.go
Labels: 1.11.2, 1.12.0

#5194 1.11 version of 5193
  src/server/auth/server/testing/auth_test.go
  src/server/pfs/server/driver.go
Labels: 1.11.2, bug

#5195 1.10 version of 5193
  src/server/auth/server/testing/auth_test.go
  src/server/pfs/server/driver.go
Labels: 1.10.6

#5179 add "failed uploads" troubleshooting section
  doc/docs/1.11.x/troubleshooting/general_troubleshooting.md
  doc/docs/master/troubleshooting/general_troubleshooting.md
Labels: docs

#5201 Move egress out of standard job flow to fix early cancellation
  go.mod
  go.sum
  src/server/worker/driver/driver.go
  src/server/worker/driver/testing.go
  src/server/worker/pipeline/transform/common_test.go
  src/server/worker/pipeline/transform/registry.go
  src/server/worker/pipeline/transform/transform_test.go
Labels: 1.11.2, 1.12.0, bug

#5189 Deferred provenance bugfix
  src/server/pachyderm_test.go
  src/server/pfs/server/driver.go
  src/server/pkg/ppsutil/util.go
Labels: 1.11.2, 1.12.0, bug

#5173 Update progress when job is created
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pps/server/api_server.go
  src/server/worker/pipeline/transform/registry.go
  src/server/worker/pipeline/transform/status.go
  src/server/worker/pipeline/transform/worker.go
Labels: 1.11.2, 1.12.0

#5207 Deferred prov fix for 1.11.x
  src/server/pachyderm_test.go
  src/server/pfs/server/driver.go
  src/server/pkg/ppsutil/util.go
Labels: 1.11.2

#5206 Progress 1.11
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pps/server/api_server.go
  src/server/worker/pipeline/transform/registry.go
  src/server/worker/pipeline/transform/status.go
  src/server/worker/pipeline/transform/worker.go
Labels: 1.11.2

#5234 Expose SAML and OIDC HTTP server port configuration (1.11.x)
  src/client/portforwarder.go
  src/server/auth/server/api_server.go
  src/server/auth/server/oidc.go
  src/server/auth/server/saml.go
  src/server/cmd/pachctl/cmd/cmd.go
  src/server/cmd/pachd/main.go
  src/server/pkg/serviceenv/config.go
Labels: 1.11.3

#5227 Fix bug in run cron with build pipelines
  src/server/pachyderm_test.go
  src/server/pps/cmds/cmds_test.go
  src/server/pps/server/api_server.go
Labels: 1.11.3, 1.12.0
