Repository pachyderm/pachyderm, pull requests merged in 2020-07, with the labels that each got.

#5062 Deprecation notice for S3V2 flag (minio client)
  src/server/pkg/deploy/cmds/cmds.go
  src/server/pkg/obj/obj.go
Labels: 1.11.0

#5063 Fix dash compatibility check
  Makefile
  doc/release_instructions.md
  etc/build/dash_compatibility.sh
  etc/build/release_pachctl.sh
  go.sum
  src/client/version/client.go
  src/server/pkg/deploy/cmds/cmds.go
Labels: 1.11.0

#4987 [DOC] Add pachctl mount docs
  doc/docs/master/assets/images/s_finder_repo_mount.png
  doc/docs/master/how-tos/export-data-out-pachyderm.md
  doc/docs/master/how-tos/export-data-out-pachyderm/export-data-egress.md
  doc/docs/master/how-tos/export-data-out-pachyderm/export-data-pachctl.md
  doc/docs/master/how-tos/export-data-out-pachyderm/index.md
  doc/docs/master/how-tos/export-data-out-pachyderm/mount-repo-to-local-computer.md
  doc/mkdocs-master.yml
Labels: docs

#5074 Fix dash compatibility file read to be from a branch not a tag
  Makefile
  doc/release_instructions.md
  etc/build/dash_compatibility.sh
  go.mod
  go.sum
  src/client/version/client.go
  src/server/pkg/deploy/cmds/cmds.go
Labels: 1.11.0

#5082 Readd code to finish dangling stats commits that was lost in the worker refactor
  src/server/worker/pipeline/transform/transform.go
Labels: 1.11.0

#5086 [DOC] Update the multiple transaction section
  doc/docs/master/how-tos/use-transactions-to-run-multiple-commands.md
Labels: docs

#4975 Add Cluster-wide FS Admin role
  src/client/auth/auth.pb.go
  src/client/auth/auth.proto
  src/client/pkg/require/require.go
  src/client/transaction.go
  src/server/auth/cmds/cmds_test.go
  src/server/auth/server/api_server.go
  src/server/auth/server/testing/admin_test.go
  src/server/auth/server/testing/auth_test.go
  src/server/auth/testing/auth.go
  src/server/pfs/server/driver.go
  src/server/pkg/testpachd/mock_pachd.go
  src/server/pps/server/api_server.go
Labels: 1.11.0

#5079 Reduce size of pachctl images
  Dockerfile.pachctl
Labels: 1.11.0

#5061 More error comparison fixes
  src/server/auth/server/oidc.go
  src/server/pkg/storage/fileset/writer.go
Labels: 1.11.0

#5092 [DOC] Document GO_PERCENT
  doc/docs/master/deploy-manage/deploy/environment-variables.md
Labels: docs

#5088 [DOC] Clarify the run pipeline behavior
  src/server/pps/cmds/cmds.go
Labels: docs

#5064 Pipeline build steps
  Makefile
  etc/pipeline-build/Makefile
  etc/pipeline-build/go/Dockerfile
  etc/pipeline-build/go/build.sh
  etc/pipeline-build/go/run.sh
  etc/pipeline-build/python/Dockerfile
  etc/pipeline-build/python/build.sh
  etc/pipeline-build/python/run.sh
  etc/reset.py
  etc/testing/examples.sh
  etc/testing/pipeline-build/go/go.mod
  etc/testing/pipeline-build/go/go.sum
  etc/testing/pipeline-build/go/main.go
  etc/testing/pipeline-build/input/1.txt
  etc/testing/pipeline-build/input/11.txt
  etc/testing/pipeline-build/input/111.txt
  etc/testing/pipeline-build/python/.pachignore
  etc/testing/pipeline-build/python/foo.txt
  etc/testing/pipeline-build/python/main.py
  etc/testing/pipeline-build/python/requirements.txt
  etc/testing/travis.sh
  etc/testing/travis_build.sh
  examples/word_count/Makefile
  examples/word_count/README.md
  examples/word_count/map/map.go
  examples/word_count/map/map.json
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pfs/cmds/cmds_test.go
  src/server/pkg/hashtree/hashtree_test.go
  src/server/pps/cmds/cmds.go
  src/server/pps/cmds/cmds_test.go
  src/server/pps/server/api_server.go
  src/server/pps/server/githook/githook.go
Labels: 1.11.0, needs docs

#5095 Readd commit traversal recovery code
  src/server/worker/pipeline/transform/registry.go
Labels: 1.11.0

#4946 Loki Logging
  Makefile
  etc/testing/travis.sh
  etc/testing/travis_install.sh
  go.mod
  go.sum
  src/client/pps.go
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pachyderm_test.go
  src/server/pkg/lokiutil/lokiutil.go
  src/server/pkg/serviceenv/config.go
  src/server/pkg/serviceenv/service_env.go
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
  src/server/pps/server/worker_rc.go
Labels: 1.11.0

#5023 PFS-over-HTTP supports TLS
  src/server/cmd/pachd/main.go
Labels: 1.11.0

#5089 Makes gc percent configurable.
  src/server/cmd/pachd/main.go
  src/server/pkg/serviceenv/config.go
  src/server/pps/server/api_server.go
  src/server/pps/server/server.go
  src/server/pps/server/worker_rc.go
Labels: 1.11.0, needs docs

#4933 [WIP][DOC]Add OIDC doc changes
  doc/docs/master/assets/images/s_auth0_grant_settings.png
  doc/docs/master/assets/images/s_keycloak_client.png
  doc/docs/master/assets/images/s_keycloak_login.png
  doc/docs/master/enterprise/auth/auth-config.md
  doc/docs/master/enterprise/auth/enable-auth.md
  doc/docs/master/enterprise/auth/index.md
  doc/docs/master/enterprise/auth/manage-users-groups.md
  doc/docs/master/enterprise/auth/oidc/configure-auth0.md
  doc/docs/master/enterprise/auth/oidc/configure-google-oidc.md
  doc/docs/master/enterprise/auth/oidc/configure-keycloak.md
  doc/docs/master/enterprise/auth/oidc/index.md
  doc/docs/master/enterprise/auth/saml/saml.md
  doc/docs/master/enterprise/auth/saml/saml_setup.md
  doc/docs/master/enterprise/auth/saml/saml_usage.md
  doc/docs/master/enterprise/index.md
  doc/mkdocs-master.yml
Labels: 1.11.0, docs

#5101 Fuse warning
  src/server/pfs/cmds/mount_darwin.go
  src/server/pfs/cmds/mount_linux.go
  src/server/pfs/cmds/mount_unix.go
Labels: 1.11.0

#5108 [DOC] Add 1.11.x to the doc dropdown
  doc/docs/1.10.x/getting_started/local_installation.md
  doc/docs/1.11.x/getting_started/local_installation.md
  doc/docs/1.9.x/getting_started/local_installation.md
  doc/overrides/partials/versions.html
Labels: docs

#5105 'pachctl debug pprof' and PPS_NAMESPACE bug fixes for 1.10.x
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  src/server/debug/cmds/cmds.go
  src/server/pkg/deploy/assets/assets.go
  src/server/pps/server/worker_rc.go
Labels: 1.10.6

#5136 Add job finished error type, and use it in finish / recover job (1.11.x)
  src/server/pps/pps.go
  src/server/pps/server/api_server.go
  src/server/worker/pipeline/transform/registry.go
Labels: 1.11.1

#5150 Debugging improvements (1.11.x)
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  src/client/debug.go
  src/client/debug/debug.pb.go
  src/client/debug/debug.proto
  src/client/transaction.go
  src/server/cmd/pachctl/cmd/compat.go
  src/server/cmd/pachd/main.go
  src/server/cmd/worker/main.go
  src/server/debug/cmds/cmds.go
  src/server/debug/server/server.go
  src/server/debug/server/util.go
  src/server/pachyderm_test.go
  src/server/pkg/deploy/assets/assets.go
  src/server/pkg/serviceenv/config.go
  src/server/pps/cmds/cmds.go
  src/server/pps/pretty/pretty.go
  src/server/pps/server/worker_rc.go
  src/server/worker/server/client.go
Labels: 1.11.1

#5119 [DOC] Add redirects for 1.11.x
  doc/netlify.toml
Labels: docs

#5138 Example/housing prices
  examples/Makefile
  examples/ml/housing-prices/Dockerfile
  examples/ml/housing-prices/README.md
  examples/ml/housing-prices/data/housing-simplified-1.csv
  examples/ml/housing-prices/data/housing-simplified-2.csv
  examples/ml/housing-prices/images/corr_matrix-1.png
  examples/ml/housing-prices/images/corr_matrix-2.png
  examples/ml/housing-prices/images/cv_reg_output-1.png
  examples/ml/housing-prices/images/cv_reg_output-2.png
  examples/ml/housing-prices/images/learning_curve-1.png
  examples/ml/housing-prices/images/pairplot-1.png
  examples/ml/housing-prices/images/pairplot-2.png
  examples/ml/housing-prices/images/regression_pipeline.png
  examples/ml/housing-prices/regression.json
  examples/ml/housing-prices/regression.py
  examples/ml/housing-prices/utils.py
Labels: docs

#5126 [DOC] Fix a typo
  doc/docs/1.11.x/reference/pipeline_spec.md
  doc/docs/master/reference/pipeline_spec.md
Labels: docs
