Repository pachyderm/pachyderm, pull requests merged in 2020-10, with the labels that each got.

#5302 Check for boundary condition when skipping blocks
  src/server/pfs/server/obj_block_api_server.go
Labels: 1.11.5, 1.12.0

#5303 Fixing pachctl hanging on connecting on windows
  src/client/client.go
Labels: bug

#5316 Check for boundary condition when skipping blocks
  src/server/pfs/server/obj_block_api_server.go
Labels: 1.11.5

#5314 Fix update pipeline with reprocess and stats
  src/server/pachyderm_test.go
  src/server/pps/server/api_server.go
Labels: 1.11.5, 1.12.0

#5321 Fix update pipeline with reprocess and stats (1.11.x)
  src/server/pachyderm_test.go
  src/server/pps/server/api_server.go
Labels: 1.11.5

#5324 Change delete job to stop the job before deleting it
  src/server/pachyderm_test.go
  src/server/pps/server/api_server.go
Labels: 1.11.5, 1.12.0

#5326 Change delete job to stop the job before deleting it (1.11.x)
  src/server/pachyderm_test.go
  src/server/pps/server/api_server.go
Labels: 1.11.5

#5322 Better handling of incomplete get pipeline info when PFS objects are unavailable
  go.mod
  go.sum
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/auth/server/testing/oidc_test.go
  src/server/cmd/pachctl/cmd/cmd.go
  src/server/cmd/pachctl/shell/completions.go
  src/server/pachyderm_test.go
  src/server/pkg/metrics/metrics.go
  src/server/pkg/ppsutil/util.go
  src/server/pps/cmds/cmds.go
  src/server/pps/pretty/pretty.go
  src/server/pps/server/api_server.go
Labels: 1.11.5, 1.12.0

#5352 Set WhoAmI log level to debug.
  src/server/auth/server/api_server.go
Labels: 1.11.5

#5363 Fix deadlock in monitorPipeline & refactor
  src/server/pachyderm_test.go
  src/server/pkg/backoff/retry.go
  src/server/pps/server/master.go
  src/server/pps/server/monitor.go
  src/server/pps/server/pipeline_controller.go
Labels: 1.11.5, 1.12.0

#5364 Fix deadlock in monitorPipeline & refactor
  go.mod
  go.sum
  src/server/pachyderm_test.go
  src/server/pkg/backoff/retry.go
  src/server/pps/server/master.go
  src/server/pps/server/monitor.go
  src/server/pps/server/pipeline_controller.go
Labels: 1.11.5

#5366 Clean glob before extracting capture groups
  src/server/pkg/hashtree/db.go
  src/server/pkg/hashtree/hashtree_test.go
  src/server/pkg/hashtree/path.go
  src/server/pkg/hashtree/sorted_list.go
  src/server/pkg/hashtree/sorted_list_test.go
  src/server/worker/datum/iterator.go
  src/server/worker/datum/iterator_test.go
Labels: 1.11.5

#5369 Change metric interval to 60m
  src/server/pkg/metrics/segment.go
Labels: 1.11.5, 1.12.0

#5375 Change metric interval to 60m
  src/server/pkg/metrics/segment.go
Labels: 1.11.5

#5367 Clean glob before extracting capture groups
  src/server/pfs/server/driver.go
  src/server/pkg/hashtree/db.go
  src/server/pkg/hashtree/hashtree_test.go
  src/server/pkg/hashtree/sorted_list.go
  src/server/pkg/hashtree/sorted_list_test.go
  src/server/pkg/path/path.go
  src/server/pkg/path/path_test.go
  src/server/pps/server/api_server.go
  src/server/worker/datum/iterator.go
  src/server/worker/datum/iterator_bench_test.go
  src/server/worker/datum/iterator_test.go
Labels: 1.12.0

#5388 Use non-expiring tokens for PPS pipelines
  src/server/pps/server/api_server.go
Labels: 1.11.5

#5330 More changes to allow CRASHING -> STANDBY
  .travis.yml
  etc/testing/travis_build_check_and_stash.sh
  etc/testing/travis_failure.sh
  etc/testing/travis_test_check_and_pull.sh
  src/server/pachyderm_test.go
  src/server/pkg/ppsutil/util.go
  src/server/pps/server/api_server.go
  src/server/pps/server/master.go
  src/server/pps/server/monitor.go
  src/server/pps/server/pipeline_controller.go
  src/server/pps/server/poller.go
Labels: 1.11.5
