Repository pachyderm/pachyderm, pull requests merged in 2020-05, with the labels that each got.

#4840 Set commit Started/Finished during Extract and Restore
  etc/proto/Dockerfile
  src/client/enterprise/enterprise.pb.go
  src/client/pfs.go
  src/client/pfs/pfs.pb.go
  src/client/pfs/pfs.proto
  src/client/pkg/require/require.go
  src/client/pkg/tracing/extended/extended_trace.pb.go
  src/client/pkg/tracing/extended/extended_trace.proto
  src/server/admin/server/admin_test.go
  src/server/admin/server/api_server.go
  src/server/pfs/server/api_server.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/driver_new_storage.go
  src/server/pfs/server/testing/server_test.go
  src/server/pkg/hashtree/hashtree.pb.go
  src/server/worker/worker_service.pb.go
Labels: 1.10.3

#4847 Add a redirect
  netlify.toml
Labels: docs

#4849 Update links in docs to 1.10.3
  doc/docs/1.10.x/getting_started/local_installation.md
  doc/docs/master/getting_started/local_installation.md
Labels: docs

#4848 Make PutFile parallelism configurable in pachd
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  src/server/pfs/server/driver.go
  src/server/pkg/deploy/assets/assets.go
  src/server/pkg/deploy/cmds/cmds.go
  src/server/pkg/serviceenv/config.go
Labels: 1.10.4

#4859 Fix link to backup cluster
  doc/docs/1.10.x/deploy-manage/manage/migrations.md
  doc/docs/master/deploy-manage/manage/migrations.md
Labels: docs

#4836 [DOC] Add Ingress doc
  doc/Pipfile.lock
  doc/docs/master/deploy-manage/manage/configure-external-access.md
  doc/docs/master/deploy-manage/manage/expose-pach-ui-ingress.md
  doc/mkdocs-master.yml
  examples/traefik-ingress/roles.yaml
  examples/traefik-ingress/traefik-daemonset.yaml
  examples/traefik-ingress/traefik-ingress-minikube.yaml
Labels: docs

#4863 Add a google analytics tag
  doc/mkdocs-master.yml
  doc/overrides/main.html
  doc/overrides/partials/integrations/analytics.html
Labels: docs

#4873 Fix meta info
  doc/overrides/main.html
Labels: docs

#4874 [DOC] Meta tag fixes
  doc/docs/1.10.x/assets/Pachyderm-Character_stacked--1200.png
  doc/docs/1.10.x/assets/images/Pachyderm-Character_stacked--1200.png
  doc/docs/1.10.x/assets/images/Pachyderm-Character_stacked.svg
  doc/docs/master/assets/Pachyderm-Character_stacked--1200.png
  doc/docs/master/assets/images/Pachyderm-Character_stacked--1200.png
  doc/docs/master/assets/images/Pachyderm-Character_stacked.svg
  doc/mkdocs-1.10.x.yml
  doc/mkdocs-1.9.x.yml
  doc/mkdocs-master.yml
  doc/overrides/assets/images/Pachyderm-Character_stacked--1200.png
  doc/overrides/main.html
Labels: docs

#4862 Allow standby pipelines to be stopped (like #4860 for 1.10.x)
  src/client/pps/pps.proto
  src/server/pachyderm_test.go
  src/server/pps/server/master.go
  src/server/pps/server/pipeline_controller.go
Labels: 1.10.4

#4886 Fix ListDatum when called on a running job
  src/server/pachyderm_test.go
  src/server/pps/server/api_server.go
Labels: 1.10.4

#4876 Use host native DNS resolver for hostnames in grpc connections
  src/client/client.go
  src/client/pkg/grpcutil/dialer.go
Labels: 1.10.4

#4888 Fix DNS resolver in grpc
  src/client/client.go
  src/client/pkg/grpcutil/dialer.go
Labels: 1.10.4

#4897 [DOC] Add a troubleshooting section
  doc/docs/1.10.x/getting_started/local_installation.md
  doc/docs/1.10.x/troubleshooting/pipeline_troubleshooting.md
  doc/docs/master/deploy-manage/manage/pachctl_shell.md
  doc/docs/master/getting_started/local_installation.md
  doc/docs/master/troubleshooting/pipeline_troubleshooting.md
Labels: docs

#4909 [DOC] Clarify overwrite for cron inputs
  doc/docs/1.10.x/reference/pipeline_spec.md
  doc/docs/master/reference/pipeline_spec.md
Labels: docs

#4885 [DOC]Update Jupyterhub deploy docs
  doc/Pipfile
  doc/Pipfile.lock
  doc/docs/1.10.x/troubleshooting/index.md
  doc/docs/1.9.x/troubleshooting/index.md
  doc/docs/master/deploy-manage/deploy/deploy-pachyderm-ide.md
  doc/docs/master/deploy-manage/deploy/deploy-pachyderm-jupyterhub.md
  doc/docs/master/deploy-manage/manage/s3gateway/index.md
  doc/docs/master/how-tos/use-pachyderm-ide/index.md
  doc/docs/master/how-tos/use-pachyderm-ide/using-pachyderm-ide.md
  doc/docs/master/troubleshooting/index.md
  doc/mkdocs-master.yml
  netlify.toml
Labels: docs

#4931 Comment out Pachyderm IDE redirects until 1.11
  netlify.toml
Labels: docs

#4930 Add auth context to client for file requests
  src/server/http/http.go
Labels: 1.11.0
