Repository pachyderm/pachyderm, pull requests merged in 2020-03, with the labels that each got.

#4672 Treat EDITOR env var as a command with options.
  src/server/pps/cmds/cmds.go
  src/server/pps/cmds/cmds_test.go
Labels: 1.10.0

#4675 Change how resource requests are assigned to pipeline containers
  src/server/pkg/ppsutil/util.go
  src/server/pps/server/api_server.go
  src/server/pps/server/worker_rc.go
Labels: 1.10.0, 1.9.13

#4685 Fix formatting in Beginner Tutorial
  doc/docs/1.10.x/getting_started/beginner_tutorial.md
  doc/docs/master/getting_started/beginner_tutorial.md
Labels: docs

#4680 Fix some extract/restore issues.
  src/server/admin/server/convert1_9.go
Labels: 1.10.0

#4660 Add S3 inputs and outputs to pipelines
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  etc/testing/images/ubuntu_with_s3_clients/Dockerfile
  etc/testing/images/ubuntu_with_s3_clients/Makefile
  etc/testing/travis.sh
  go.mod
  go.sum
  src/server/cmd/pachd/main.go
  src/server/cmd/worker/main.go
  src/server/pachyderm_test.go
  src/server/pfs/s3/auth.go
  src/server/pfs/s3/bucket.go
  src/server/pfs/s3/client_factory.go
  src/server/pfs/s3/controller.go
  src/server/pfs/s3/driver.go
  src/server/pfs/s3/master_test.go
  src/server/pfs/s3/multipart.go
  src/server/pfs/s3/object.go
  src/server/pfs/s3/s3.go
  src/server/pfs/s3/s3_test.go
  src/server/pfs/s3/service.go
  src/server/pfs/s3/util.go
  src/server/pfs/s3/util_test.go
  src/server/pfs/s3/worker_test.go
  src/server/pkg/backoff/exponential.go
  src/server/pkg/deploy/assets/assets.go
  src/server/pkg/ppsutil/util.go
  src/server/pkg/serviceenv/config.go
  src/server/pps/server/api_server.go
  src/server/pps/server/master.go
  src/server/pps/server/s3g_sidecar.go
  src/server/pps/server/s3g_sidecar_test.go
  src/server/pps/server/server.go
  src/server/pps/server/worker_rc.go
  src/server/worker/api_server.go
  src/server/worker/datum_iterator.go
  src/server/worker/datum_iterator_test.go
  src/server/worker/master.go
  src/server/worker/worker_service.pb.go
  src/server/worker/worker_service.proto
Labels: 1.10.0

#4604 Remove master docs from the website
  doc/build.sh
  doc/material/partials/versions.html
Labels: 1.10.0, docs

#4704 Fix release doc to rebuild pachctl before regenerating manifests
  doc/release_instructions.md
  etc/build/repo_ready_for_release.sh
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  etc/testing/deploy-manifests/validate.sh
  src/server/pkg/deploy/cmds/cmds.go
Labels: 1.10.0

#4703 Don't cache processed datums when S3Out is set
  src/server/pfs/server/driver.go
  src/server/pps/server/s3g_sidecar_test.go
  src/server/worker/master.go
Labels: 1.10.0

#4658 Update S3 docs
  doc/docs/1.10.x/assets/images/d_kubeflow_sidecar.png
  doc/docs/1.10.x/deploy-manage/deploy/environment-variables.md
  doc/docs/1.10.x/deploy-manage/manage/s3gateway/configure-s3client.md
  doc/docs/1.10.x/deploy-manage/manage/s3gateway/deploy-s3gateway-sidecar.md
  doc/docs/1.10.x/deploy-manage/manage/s3gateway/index.md
  doc/docs/1.10.x/deploy-manage/manage/s3gateway/supported-operations.md
  doc/docs/1.10.x/deploy-manage/manage/s3gateway/unsupported-operations.md
  doc/docs/1.10.x/how-tos/export-data-out-pachyderm.md
  doc/docs/1.10.x/how-tos/load-data-into-pachyderm.md
  doc/docs/1.10.x/reference/pipeline_spec.md
  doc/docs/master/assets/images/d_kubeflow_sidecar.png
  doc/docs/master/deploy-manage/deploy/environment-variables.md
  doc/docs/master/deploy-manage/manage/s3gateway/configure-s3client.md
  doc/docs/master/deploy-manage/manage/s3gateway/deploy-s3gateway-sidecar.md
  doc/docs/master/deploy-manage/manage/s3gateway/index.md
  doc/docs/master/deploy-manage/manage/s3gateway/supported-operations.md
  doc/docs/master/deploy-manage/manage/s3gateway/unsupported-operations.md
  doc/docs/master/how-tos/export-data-out-pachyderm.md
  doc/docs/master/how-tos/load-data-into-pachyderm.md
  doc/docs/master/reference/pipeline_spec.md
  doc/mkdocs-1.10.x.yml
  doc/mkdocs-master.yml
  netlify.toml
Labels: docs

#4710 Fix broken links
  doc/docs/1.10.x/concepts/advanced-concepts/distributed_computing.md
  doc/docs/1.10.x/getting_started/beginner_tutorial.md
  doc/docs/1.10.x/getting_started/install-pachctl-completion.md
  doc/docs/1.10.x/getting_started/local_installation.md
  doc/docs/1.10.x/how-tos/create-pipeline.md
  doc/docs/1.10.x/how-tos/delete-pipeline.md
  doc/docs/1.10.x/reference/pipeline_spec.md
  doc/docs/master/concepts/advanced-concepts/distributed_computing.md
  doc/docs/master/deploy-manage/manage/index.md
  doc/docs/master/getting_started/beginner_tutorial.md
  doc/docs/master/getting_started/install-pachctl-completion.md
  doc/docs/master/getting_started/local_installation.md
  doc/docs/master/how-tos/create-pipeline.md
  doc/docs/master/how-tos/delete-pipeline.md
  doc/docs/master/how-tos/use-transactions-to-run-multiple-commands.md
  doc/docs/master/index.md
  doc/docs/master/reference/pipeline_spec.md
  netlify.toml
Labels: docs

#4692 Update the migration docs
  doc/docs/master/assets/javascripts/extra.js
  doc/docs/master/assets/stylesheets/extra.css
  doc/docs/master/deploy-manage/manage/backup_restore.md
  doc/docs/master/deploy-manage/manage/migrations.md
  doc/mkdocs-master.yml
  netlify.toml
Labels: 1.10.0, docs

#4721 Fix path name
  doc/build.sh
Labels: bug, docs

#4723 [DOC] Add DISABLE_COMMIT_PROGRESS_COUNTER description
  doc/docs/1.10.x/deploy-manage/deploy/environment-variables.md
  doc/docs/master/deploy-manage/deploy/environment-variables.md
Labels: docs

#4724 Cherry-pick the migration doc to 1.10.x
  doc/docs/1.10.x/assets/javascripts/extra.js
  doc/docs/1.10.x/assets/stylesheets/extra.css
  doc/docs/1.10.x/deploy-manage/manage/backup_restore.md
  doc/docs/1.10.x/deploy-manage/manage/migrations.md
  doc/mkdocs-1.10.x.yml
Labels: docs

#4733 Fix JupyterHub links
  netlify.toml
Labels: docs

#4752 Include namespace in S3_ENDPOINT in worker (1.10.x)
  src/server/pkg/serviceenv/service_env.go
  src/server/pps/server/s3g_sidecar_test.go
  src/server/worker/api_server.go
Labels: 1.10.1

#4747 Fix spout input bug
  go.mod
  go.sum
  src/server/pachyderm_test.go
  src/server/pps/server/api_server.go
Labels: 1.10.1
