Repository pachyderm/pachyderm, pull requests merged in 2020-12, with the labels that each got.

#5468 Chunk writes in putObjWriteCloser
  src/client/pfs.go
  src/client/pkg/grpcutil/stream.go
  src/server/worker/logs/logger.go
Labels: 1.11.8, 1.12.0

#5466 Fixes issue with boltdb cursor usage when deleting directories (1.11.x)
  src/server/pfs/server/testing/server_test.go
  src/server/pkg/hashtree/db.go
Labels: 1.11.8

#5461 Split transaction implementation
  src/client/pfs.go
  src/client/pfs/pfs.pb.go
  src/client/pfs/pfs.proto
  src/client/pps.go
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pachyderm_test.go
  src/server/pfs/cmds/cmds.go
  src/server/pfs/pfs.go
  src/server/pfs/server/api_server.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/testing/server_test.go
  src/server/pfs/server/trigger.go
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
Labels: 1.11.8, 1.12.0

#5477 Chunk writes in putObjWriteCloser
  src/client/pfs.go
  src/client/pkg/grpcutil/stream.go
  src/server/worker/logs/logger.go
Labels: 1.11.8

#5482 Split transaction implementation (1.11.x)
  src/client/pfs.go
  src/client/pfs/pfs.pb.go
  src/client/pfs/pfs.proto
  src/client/pps.go
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pachyderm_test.go
  src/server/pfs/cmds/cmds.go
  src/server/pfs/pfs.go
  src/server/pfs/server/api_server.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/testing/block_api_server_test.go
  src/server/pfs/server/testing/server_test.go
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
Labels: 1.11.8

#5479 Backport disabling grpc service config lookup to 1.11.x
  src/client/client.go
Labels: 1.11.8

#5447 Basic group input docs
  doc/docs/master/reference/pipeline_spec.md
Labels: docs

#5483 Pipeline triggers
  doc/docs/master/concepts/advanced-concepts/deferred_processing.md
  doc/docs/master/reference/pipeline_spec.md
  go.mod
  go.sum
  src/client/pps.go
  src/server/pachyderm_test.go
  src/server/pachyderm_validation_test.go
  src/server/pps/server/api_server.go
  src/server/worker/datum/iterator_bench_test.go
  src/server/worker/datum/iterator_test.go
Labels: 1.12.0, needs docs

#5512 Altered pachctl diff file command help text -
  src/server/pfs/cmds/cmds.go
Labels: 1.12.0

#5494 Auth extract/restore
  Makefile
  src/client/admin.go
  src/client/admin/admin.pb.go
  src/client/admin/admin.proto
  src/client/auth/auth.go
  src/client/auth/auth.pb.go
  src/client/auth/auth.proto
  src/client/pkg/config/config.go
  src/client/transaction.go
  src/server/admin/cmds/cmds.go
  src/server/admin/server/admin_test.go
  src/server/admin/server/api_server.go
  src/server/auth/cmds/cmds.go
  src/server/auth/server/api_server.go
  src/server/auth/server/testing/admin_test.go
  src/server/auth/server/testing/auth_test.go
  src/server/auth/testing/auth.go
  src/server/pkg/testpachd/mock_pachd.go
  src/server/pkg/testutil/auth.go
Labels: 1.11.9, 1.12.0

#5515 Backport extract/restore support for clusters with auth to 1.11.x
  Makefile
  etc/testing/kafka/Dockerfile
  src/client/admin.go
  src/client/admin/admin.pb.go
  src/client/admin/admin.proto
  src/client/auth/auth.go
  src/client/auth/auth.pb.go
  src/client/auth/auth.proto
  src/client/pkg/config/config.go
  src/client/transaction.go
  src/server/admin/cmds/cmds.go
  src/server/admin/server/admin_test.go
  src/server/admin/server/api_server.go
  src/server/auth/cmds/cmds.go
  src/server/auth/server/api_server.go
  src/server/auth/server/testing/admin_test.go
  src/server/auth/server/testing/auth_test.go
  src/server/auth/testing/auth.go
  src/server/pkg/testpachd/mock_pachd.go
  src/server/pkg/testutil/auth.go
Labels: 1.11.9

#5530 Don't use the same host path for hashtree caches across workers in a local deployment
  src/server/cmd/pachd/main.go
  src/server/cmd/worker/main.go
  src/server/pkg/serviceenv/config.go
  src/server/pps/server/api_server.go
  src/server/pps/server/server.go
  src/server/pps/server/worker_rc.go
Labels: bug, test flake

#5538 Fix incorrect trigger behavior on pipeline update and race condition on triggering with rapid commits
  .vscode/tasks.json
  src/server/pfs/server/trigger.go
  src/server/pps/server/api_server.go
Labels: 1.12.0, bug

#5539 Only check admin witnesses once
  src/server/auth/server/api_server.go
Labels: 1.12.0

#5431 Create pipeline info transactionally
  src/client/transaction.go
  src/client/transaction/transaction.pb.go
  src/client/transaction/transaction.proto
  src/server/pachyderm_test.go
  src/server/pfs/server/api_server.go
  src/server/pfs/server/transaction_defer.go
  src/server/pkg/testpachd/mock_transaction.go
  src/server/pkg/transactionenv/env.go
  src/server/pkg/transactionenv/testing.go
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
  src/server/transaction/cmds/cmds.go
  src/server/transaction/pretty/pretty.go
  src/server/transaction/server/driver.go
  src/server/transaction/server/testing/server_test.go
Labels: 1.12.0

#5532 Support extract/restore from 1.11
  etc/testing/migration/v1_11/auth.metadata
  etc/testing/migration/v1_11/auth.sh
  etc/testing/migration/v1_11/deploy.sh
  src/client/admin/admin.pb.go
  src/client/admin/admin.proto
  src/client/admin/v1_11/auth/auth.pb.go
  src/client/admin/v1_11/auth/auth.proto
  src/client/admin/v1_11/enterprise/enterprise.pb.go
  src/client/admin/v1_11/enterprise/enterprise.proto
  src/server/admin/server/admin_test.go
  src/server/admin/server/api_server.go
  src/server/admin/server/convert1_11.go
Labels: 1.12.0

#5528 Auth support for new spouts
  go.mod
  go.sum
  src/client/client.go
  src/client/pkg/config/config.go
  src/server/auth/cmds/cmds.go
  src/server/cmd/pachctl/cmd/cmd.go
  src/server/cmd/pachctl/shell/shell.go
  src/server/config/cmds.go
  src/server/pachyderm_test.go
  src/server/pkg/deploy/cmds/cmds.go
  src/server/pkg/metrics/metrics.go
  src/server/pkg/testutil/auth.go
  src/server/pps/server/api_server.go
  src/server/pps/server/master.go
  src/server/pps/server/worker_rc.go
  src/server/transaction/cmds/util.go
Labels: 1.12.0

#5550 Build steps cleanup after goreleaser
  etc/build/repo_ready_for_release.sh
Labels: 1.12.0
