Repository pachyderm/pachyderm, pull requests merged in 2020-09, with the labels that each got.

#5237 Spout improvements
  src/server/pachyderm_test.go
  src/server/pkg/backoff/retry.go
  src/server/worker/pipeline/common.go
Labels: 1.11.3, 1.12.0

#5240 Spout improvements (1.11.x)
  src/server/pachyderm_test.go
  src/server/pkg/backoff/retry.go
  src/server/worker/pipeline/common.go
Labels: 1.11.3

#5241 Run cron fix 1.11.x
  src/server/pachyderm_test.go
  src/server/pps/server/api_server.go
Labels: 1.11.3

#5273 Disallow transition from standby to crashing
  src/server/pkg/ppsutil/util.go
Labels: 1.11.4, 1.12.0

#5288 Fix goroutine leak in work pkg (1.11.x)
  src/server/pkg/work/work.go
Labels: 1.11.4

#5225 Branch triggers
  go.mod
  go.sum
  src/client/pfs.go
  src/client/pfs/pfs.pb.go
  src/client/pfs/pfs.proto
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pachyderm_test.go
  src/server/pfs/cmds/cmds.go
  src/server/pfs/pretty/pretty.go
  src/server/pfs/server/api_server.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/testing/server_test.go
  src/server/pfs/server/trigger.go
Labels: 1.12.0, needs docs

#5291 Run Pipeline fixes
  go.mod
  go.sum
  src/server/pachyderm_test.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/testing/server_test.go
  src/server/pkg/cmdutil/cobra.go
  src/server/pps/cmds/cmds.go
  src/server/pps/cmds/cmds_test.go
  src/server/pps/server/api_server.go
Labels: 1.11.4

#5292 Support OIDC ID tokens in Authenticate
  go.mod
  src/client/auth/auth.pb.go
  src/client/auth/auth.proto
  src/server/auth/server/api_server.go
  src/server/auth/server/oidc.go
Labels: 1.12.0

#5304 Fix error printing in list pipeline
  src/server/pps/cmds/cmds.go
Labels: 1.11.5, bug
