Repository pachyderm/pachyderm, pull requests merged in 2020-06, with the labels that each got.

#4902 Improved s3gateway compatibility
  Makefile
  etc/reset.py
  etc/testing/s3gateway/ignore.conf
  etc/testing/travis.sh
  go.mod
  go.sum
  src/server/cmd/pachd/main.go
  src/server/pfs/s3/auth.go
  src/server/pfs/s3/bucket.go
  src/server/pfs/s3/client_factory.go
  src/server/pfs/s3/driver.go
  src/server/pfs/s3/error.go
  src/server/pfs/s3/multipart.go
  src/server/pfs/s3/object.go
  src/server/pfs/s3/s3.go
  src/server/pfs/s3/service.go
  src/server/pfs/s3/util_test.go
  src/server/pkg/errutil/errutil.go
  src/server/pkg/hashtree/db.go
  src/server/pkg/log/log.go
  src/server/pps/server/s3g_sidecar.go
Labels: needs docs

#4942 Add a redirect from /en/latest/
  netlify.toml
Labels: docs

#4940 [DOC] Clarify the env var description
  doc/docs/1.10.x/deploy-manage/deploy/environment-variables.md
  doc/docs/1.10.x/reference/pipeline_spec.md
  doc/docs/master/deploy-manage/deploy/environment-variables.md
  doc/docs/master/reference/pipeline_spec.md
Labels: docs

#4962 Add keepalive to default grpc options (1.10.x)
  src/client/client.go
  src/server/pkg/serviceenv/service_env.go
Labels: 1.10.5

#4963 Put worker status collection behind a full flag in inspect job (1.10.x)
  src/client/pps.go
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pachyderm_test.go
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
Labels: 1.10.5

#4964 Collect sidecar goroutine dumps in debug dump (1.10.x)
  src/server/cmd/pachd/main.go
  src/server/cmd/worker/main.go
  src/server/debug/server/server.go
Labels: 1.10.5

#4965 Fix duplicate datums in stats commit when retries occurred (1.10.x)
  src/server/worker/api_server.go
Labels: 1.10.5

#4934 [DOC] Add "Monitor Job Progress"
  doc/docs/master/assets/images/demo-progress-bar1.yml
  doc/docs/master/assets/images/list_commit_progress_bar.gif
  doc/docs/master/how-tos/monitor-job-progress.md
  doc/mkdocs-master.yml
Labels: docs

#5000 [DOC] ignore netlify build for other dirs
  doc/docs/master/troubleshooting/general_troubleshooting.md
  doc/netlify.toml
Labels: docs

#4999 Add configurable limits for the worker sidecar in PPS pipeline specs
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pkg/ppsutil/util.go
  src/server/pps/pretty/pretty.go
  src/server/pps/server/api_server.go
  src/server/pps/server/worker_rc.go
Labels: 1.10.5, needs docs

#5003 Set env vars in services and spouts (1.10.x)
  src/server/pachyderm_test.go
  src/server/pkg/serviceenv/service_env.go
  src/server/worker/master.go
Labels: 1.10.5

#4976 [DOC] Add a note about AWS bucket encryption
  doc/docs/1.10.x/deploy-manage/deploy/amazon_web_services/aws-deploy-pachyderm.md
  doc/docs/master/deploy-manage/deploy/amazon_web_services/aws-deploy-pachyderm.md
Labels: docs

#4989 [DOC] Clarify access permissions
  doc/docs/1.10.x/deploy-manage/deploy/rbac.md
  doc/docs/master/deploy-manage/deploy/rbac.md
Labels: docs

#4991 [DOC] Clarify err_cmd
  doc/docs/1.10.x/how-tos/err_cmd.md
  doc/docs/master/how-tos/err_cmd.md
Labels: docs

#5032 [DOC] Add sidecar_resource_limits to pipeline spec.
  doc/docs/1.10.x/reference/pipeline_spec.md
  doc/docs/master/reference/pipeline_spec.md
Labels: docs

#5040 [DOC] Add a node to local install
  doc/docs/1.10.x/getting_started/local_installation.md
  doc/docs/master/getting_started/local_installation.md
Labels: docs

#5009 Set env vars in services and spouts
  src/server/pachyderm_test.go
  src/server/worker/driver/driver.go
  src/server/worker/driver/testing.go
  src/server/worker/pipeline/common.go
  src/server/worker/pipeline/service/service.go
  src/server/worker/pipeline/spout/spout.go
  src/server/worker/pipeline/transform/worker.go
Labels: 1.11.0, bug

#5026 [DOC] Add "Mount a Volume in a Pipeline"
  doc/docs/1.10.x/how-tos/mount-volume.md
  doc/docs/master/how-tos/mount-volume.md
  doc/mkdocs-1.10.x.yml
  doc/mkdocs-master.yml
Labels: docs

#5010 Fixed overwriting old transaction id with new one
  src/server/transaction/cmds/cmds.go
Labels: 1.11.0

#4996 Added colors to the output logs
  src/server/pps/cmds/cmds.go
Labels: 1.11.0

#5050 Fix spout spec commit subvenance growth
  src/server/pachyderm_test.go
  src/server/pfs/server/driver.go
Labels: 1.10.6

#4910 Make pipelines more robust to potential missing objects
  src/server/cmd/worker/main.go
  src/server/pkg/ppsutil/util.go
  src/server/pps/server/api_server.go
  src/server/pps/server/pipeline_controller.go
Labels: 1.11.0

#5054 Add tests for malformed pipeline creation requests and fix some bugs
  src/client/pkg/errors/errors.go
  src/client/pps/util.go
  src/server/pachyderm_test.go
  src/server/pfs/server/driver.go
  src/server/pps/server/api_server.go
  src/server/worker/driver/driver_unix.go
Labels: 1.11.0

#5005 Implement OIDC auth
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  go.mod
  go.sum
  src/client/auth/auth.pb.go
  src/client/auth/auth.proto
  src/client/pkg/config/config.go
  src/client/pkg/tracing/pipelinetrace.pb.go
  src/client/transaction.go
  src/server/auth/cmds/cmds.go
  src/server/auth/server/api_server.go
  src/server/auth/server/config.go
  src/server/auth/server/oidc.go
  src/server/auth/testing/auth.go
  src/server/cmd/pachctl/cmd/cmd.go
  src/server/pkg/deploy/assets/assets.go
  src/server/pkg/hashtree/hashtree_test.go
  src/server/pkg/serviceenv/service_env.go
  src/server/pkg/testpachd/mock_pachd.go
Labels: 1.11.0

#5056 Make worker service account configurable
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  src/server/pkg/deploy/assets/assets.go
  src/server/pkg/deploy/cmds/cmds.go
  src/server/pps/server/worker_rc.go
Labels: 1.10.6, 1.11.0
