Repository pachyderm/pachyderm, pull requests merged in 2020-11, with the labels that each got.

#5402 Fix race condition when writing datum list job artifact in the worker master
  src/server/worker/pipeline/transform/registry.go
Labels: bug

#5401 Fixes for PutObjDirect and default values for amazon object client env vars
  src/client/pfs.go
  src/server/pfs/server/testing/block_api_server_test.go
  src/server/pkg/cmdutil/env.go
  src/server/pkg/obj/amazon_client.go
  src/server/pkg/obj/obj.go
  src/server/worker/pipeline/transform/registry.go
Labels: bug

#5395 Print egressing state
  src/server/pps/pretty/pretty.go
Labels: 1.11.6

#5411 print egressing state
  src/server/pps/pretty/pretty.go
Labels: 1.11.6

#5341 Add deploy option to enable s3 client verbose log
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  src/server/pfs/server/driver.go
  src/server/pkg/deploy/assets/assets.go
  src/server/pkg/deploy/cmds/cmds.go
  src/server/pkg/obj/amazon_client.go
  src/server/pkg/obj/obj.go
Labels: 1.11.6, 1.12.0

#5309 Outer joins
  doc/docs/master/concepts/pipeline-concepts/datum/join.md
  doc/docs/master/reference/pipeline_spec.md
  go.mod
  go.sum
  src/client/pps.go
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pachyderm_test.go
  src/server/pachyderm_validation_test.go
  src/server/worker/common/common.proto
  src/server/worker/datum/iterator.go
  src/server/worker/datum/iterator_bench_test.go
  src/server/worker/datum/iterator_test.go
Labels: 1.12.0, needs docs

#5465 [Docs] Added variable in mkdocs yml to manage latest pach version
  doc/docs/1.11.x/deploy-manage/manage/migrations.md
  doc/docs/1.11.x/deploy-manage/manage/upgrades.md
  doc/docs/master/deploy-manage/deploy/amazon_web_services/aws-deploy-pachyderm.md
  doc/docs/master/deploy-manage/deploy/azure.md
  doc/docs/master/deploy-manage/deploy/deploy-pachyderm-ide.md
  doc/docs/master/deploy-manage/deploy/google_cloud_platform.md
  doc/docs/master/deploy-manage/deploy/ibmcloud-openshift.md
  doc/docs/master/deploy-manage/deploy/openshift.md
  doc/docs/master/deploy-manage/manage/backup_restore.md
  doc/docs/master/deploy-manage/manage/migrations.md
  doc/docs/master/deploy-manage/manage/upgrades.md
  doc/docs/master/deploy-manage/manage/upgrades_migrations.md
  doc/docs/master/enterprise/deployment.md
  doc/docs/master/getting_started/local_installation.md
  doc/docs/master/getting_started/wsl-deploy.md
  doc/docs/master/pachhub/pachhub_getting_started.md
  doc/docs/master/troubleshooting/general_troubleshooting.md
  doc/mkdocs-master.yml
Labels: 1.12.0, docs

#5449 Fixes issue with boltdb cursor usage when deleting directories
  src/server/pfs/server/testing/server_test.go
  src/server/pkg/hashtree/db.go
Labels: 1.11.8, 1.12.0

#5463 [Docs] Doc environment set up and hotreload
  Dockerfile.pachdoc
  Dockerfile.pachdoc.dockerignore
  doc/README.md
  doc/docker-compose.yml
Labels: docs

#5473 Make debug API compatible with auth (1.11.x)
  src/server/auth/server/testing/auth_test.go
  src/server/debug/server/server.go
  src/server/pachyderm_test.go
Labels: 1.11.8
