Repository pachyderm/pachyderm, pull requests merged in 2020-04, with the labels that each got.

#4758 Update dash version to 0.5.48
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  src/server/pkg/deploy/cmds/cmds.go
Labels: 1.10.1

#4756 update dash version to 0.5.48
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  src/server/pkg/deploy/cmds/cmds.go
Labels: 1.10.1

#4768 fixed links to kops documentation
  doc/docs/master/deploy-manage/deploy/amazon_web_services/aws-deploy-kubernetes-kops.md
Labels: docs

#4732 Native JupyterHub deployments
  etc/reset.py
  go.mod
  go.sum
  src/client/client.go
  src/client/pkg/config/config.go
  src/client/pkg/helm/config.go
  src/client/pkg/helm/deploy.go
  src/client/pkg/helm/destroy.go
  src/server/auth/cmds/cmds.go
  src/server/cmd/pachctl/cmd/cmd.go
  src/server/cmd/pachctl/shell/shell.go
  src/server/config/cmds.go
  src/server/pkg/cmdutil/exec.go
  src/server/pkg/deploy/cmds/cmds.go
  src/server/transaction/cmds/util.go
Labels: needs docs

#4792 Godoc examples
  doc/docs/master/contributing/docs-style-guide.md
  doc/docs/master/reference/clients.md
  examples/opencv/goclient-example/README.md
  examples/opencv/goclient-example/opencv-example.go
  go.mod
  go.sum
  src/client/godoc_test.go
Labels: docs

#4782 Fix pipeline restart
  src/server/pachyderm_test.go
  src/server/pps/server/pipeline_controller.go
Labels: 1.10.2

#4793 Add METRICS_ENDPOINT to configure pachd metrics
  src/server/pkg/metrics/metrics.go
  src/server/pkg/metrics/router.go
  src/server/pkg/serviceenv/config.go
Labels: 1.10.2

#4796 Fix pipeline restart 1.10.x
  src/server/pachyderm_test.go
  src/server/pps/server/pipeline_controller.go
Labels: 1.10.2

#4801 Add instructions on how to preview images on macOS Catalina
  doc/docs/1.10.x/getting_started/beginner_tutorial.md
  doc/docs/master/getting_started/beginner_tutorial.md
Labels: docs

#4825 Clarify pipeline creation
  doc/Pipfile
  doc/Pipfile.lock
  doc/docs/1.10.x/deploy-manage/manage/s3gateway/deploy-s3gateway-sidecar.md
  doc/docs/1.10.x/how-tos/create-pipeline.md
  doc/docs/master/deploy-manage/manage/s3gateway/deploy-s3gateway-sidecar.md
  doc/docs/master/getting_started/beginner_tutorial.md
  doc/docs/master/how-tos/create-pipeline.md
  doc/mkdocs-master.yml
Labels: docs

#4822 Fix issue with using MaxMsgSize as payload size (1.10.x)
  src/client/pkg/grpcutil/stream.go
Labels: 1.10.3

#4829 Fix links to a gist and the diagram
  examples/kubeflow/mnist/README.md
Labels: docs

#4828 [DOC]Update default resource request description
  doc/docs/1.10.x/reference/pipeline_spec.md
  doc/docs/master/reference/pipeline_spec.md
Labels: docs

#4831 [DOC] Clarify the loading data to pachyderm section
  doc/docs/1.10.x/assets/images/d_steps_analysis_pipeline.svg
  doc/docs/1.10.x/how-tos/individual-developer-workflow.md
  doc/docs/1.10.x/how-tos/load-data-into-pachyderm.md
  doc/docs/master/assets/images/d_steps_analysis_pipeline.svg
  doc/docs/master/how-tos/individual-developer-workflow.md
  doc/docs/master/how-tos/load-data-into-pachyderm.md
Labels: docs

#4824 Fix incorrect read size when performing range blob reads on microsoft object client
  src/client/pkg/errors/errors.go
  src/server/pfs/server/driver.go
  src/server/pkg/obj/local_client.go
  src/server/pkg/obj/microsoft_client.go
  src/server/pkg/obj/minio_client.go
  src/server/pkg/obj/obj.go
Labels: 1.10.3

#4837 [DOC] Fix S3 path description
  doc/docs/1.10.x/deploy-manage/manage/s3gateway/supported-operations.md
  doc/docs/1.10.x/getting_started/local_installation.md
  doc/docs/1.9.x/getting_started/local_installation.md
  doc/docs/master/deploy-manage/manage/s3gateway/supported-operations.md
  doc/docs/master/getting_started/local_installation.md
  src/server/cmd/pachctl/cmd/compat.go
Labels: bug, docs

#4833 [DOC] Expand the compress parameter description
  src/server/pfs/cmds/cmds.go
Labels: docs
