Repository pachyderm/pachyderm, pull requests merged in 2021-07, with the labels that each got.

#6502 Minor wording changes
  doc/docs/master/concepts/advanced-concepts/globalID.md
  doc/docs/master/concepts/data-concepts/commit.md
Labels: docs

#6567 Combine jobset and commitset pachctl commands into 'list job' and 'list commit'
  src/server/pfs/cmds/cmds.go
  src/server/pfs/pretty/pretty.go
  src/server/pfs/server/driver.go
  src/server/pps/cmds/cmds.go
  src/server/pps/cmds/cmds_test.go
  src/server/pps/pretty/pretty.go
Labels: 2.0.0

#6618 Fix additional help topics in base `pachctl` command
  src/server/cmd/pachctl/cmd/cmd.go
Labels: 2.0.0, bug

#6627 Fix listing of jobsets after a squash, and `list job` with --pipeline without --expand flag
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
Labels: 2.0.0, bug
