Repository pachyderm/pachyderm, pull requests merged in 2021-06, with the labels that each got.

#6226 Create default empty branch head commits
  src/server/pfs/cmds/cmds.go
  src/server/pfs/fuse/loopback.go
  src/server/pfs/pfs.go
  src/server/pfs/s3/bucket.go
  src/server/pfs/s3/driver.go
  src/server/pfs/s3/multipart.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/driver_file.go
  src/server/pfs/server/driver_fsck.go
  src/server/pfs/server/testing/server_test.go
  src/server/pfs/server/trigger.go
  src/server/pps/server/api_server.go
  src/server/pps/server/monitor.go
Labels: 2.0.0

#6227 PPS updates for global IDs
  src/client/pps.go
  src/client/transaction.go
  src/internal/auth/interceptor.go
  src/internal/collection/errors.go
  src/internal/collection/postgres_collection.go
  src/internal/collection/types.go
  src/internal/obj/integrationtests/deployment_test.go
  src/internal/ppsdb/ppsdb.go
  src/internal/ppsutil/util.go
  src/internal/serviceenv/config.go
  src/internal/testpachd/mock_pachd.go
  src/internal/transactionenv/env.go
  src/internal/transactionenv/txncontext/context.go
  src/pfs/pfs.pb.go
  src/pfs/pfs.proto
  src/pps/pps.pb.go
  src/pps/pps.proto
  src/server/pachyderm_test.go
  src/server/pfs/cmds/cmds.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/transaction_defer.go
  src/server/pps/iface.go
  src/server/pps/pretty/pretty.go
  src/server/pps/server/api_server.go
  src/server/pps/server/s3g_sidecar.go
  src/server/pps/server/transaction_defer.go
  src/server/pps/server/worker_rc.go
  src/server/spout_test.go
  src/server/worker/pipeline/service/service.go
  src/server/worker/pipeline/transform/registry.go
  src/server/worker/pipeline/transform/transform.go
  src/server/worker/pipeline/transform/transform_test.go
Labels: 2.0.0

#6228 Remove `Commitset` collection in global IDs implementation
  src/client/pfs.go
  src/client/transaction.go
  src/internal/pfsdb/pfsdb.go
  src/internal/testpachd/mock_pachd.go
  src/internal/testpachd/mock_transaction.go
  src/internal/transactionenv/testing.go
  src/internal/transactionenv/txncontext/context.go
  src/pfs/pfs.go
  src/pfs/pfs.pb.go
  src/pfs/pfs.proto
  src/server/pachyderm_test.go
  src/server/pfs/cmds/cmds.go
  src/server/pfs/iface.go
  src/server/pfs/pfs.go
  src/server/pfs/server/api_server.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/testing/server_test.go
  src/server/pfs/server/val_server.go
  src/server/pps/server/api_server.go
  src/server/pps/server/transaction_defer.go
  src/server/transaction/pretty/pretty.go
Labels: 2.0.0

#6229 Change jobs to use the same ID as the commitset which spawned them
  src/client/pps.go
  src/internal/cmdutil/cobra.go
  src/internal/collection/etcd_collection_test.go
  src/internal/ppsdb/ppsdb.go
  src/internal/ppsutil/util.go
  src/pps/pps.pb.go
  src/pps/pps.proto
  src/server/cmd/pachctl/shell/completions.go
  src/server/pps/cmds/cmds.go
  src/server/pps/pretty/pretty.go
  src/server/pps/server/api_server.go
  src/server/pps/server/s3g_sidecar.go
  src/server/worker/datum/datum.pb.go
  src/server/worker/datum/datum.proto
  src/server/worker/datum/iterator.go
  src/server/worker/driver/driver.go
  src/server/worker/pipeline/service/service.go
  src/server/worker/pipeline/transform/chain/chain.go
  src/server/worker/pipeline/transform/chain/chain_test.go
  src/server/worker/pipeline/transform/registry.go
Labels: 2.0.0

#6230 Update PPS to use pipeline version instead of spec commit ID
  src/internal/ppsutil/util.go
  src/internal/testpachd/mock_transaction.go
  src/internal/transactionenv/env.go
  src/pps/pps.pb.go
  src/pps/pps.proto
  src/server/cmd/worker/main.go
  src/server/pps/iface.go
  src/server/pps/server/api_server.go
  src/server/pps/server/pipeline_controller.go
  src/server/pps/server/worker_rc.go
  src/server/transaction/server/driver.go
  src/transaction/transaction.pb.go
  src/transaction/transaction.proto
Labels: 2.0.0

#6272 [Doc] [skip-ci] Updated supported releases docs + fixed formatting issues
  doc/docs/1.11.x/how-tos/developer-workflow/ci-cd-integration.md
  doc/docs/1.12.x/how-tos/developer-workflow/ci-cd-integration.md
  doc/docs/1.13.x/how-tos/developer-workflow/ci-cd-integration.md
  doc/docs/master/contributing/supported-releases.md
  doc/docs/master/deploy-manage/deploy/connect-to-cluster.md
  doc/docs/master/how-tos/developer-workflow/ci-cd-integration.md
Labels: 2.0.0

#6281 Prevent crashing when canceling a put file request
  src/server/pfs/server/driver.go
Labels: 1.13.3, bug

#6382 Deprecate ide
  src/client/portforwarder.go
  src/internal/deploy/cmds/cmds.go
  src/internal/deploy/cmds/ide.go
  src/server/cmd/pachctl/cmd/cmd.go
Labels: needs docs

#6381 Deprecate import/export images
  src/internal/deploy/cmds/cmds.go
  src/internal/deploy/images/images.go
Labels: needs docs

#6383 Deprecate deploy storage
  src/internal/deploy/cmds/cmds.go
Labels: needs docs

#6380 Deprecate old dash from core pach
  src/client/portforwarder.go
  src/internal/deploy/assets/assets.go
  src/internal/deploy/cmds/cmds.go
  src/internal/deploy/cmds/cmds_test.go
  src/internal/obj/integrationtests/deployment_test.go
  src/server/cmd/pachctl/cmd/cmd.go
Labels: needs docs

#6387 Remove list images command
  src/internal/deploy/assets/assets.go
  src/internal/deploy/cmds/cmds.go
Labels: needs docs

#6418 Remove old IAM role annotation
  src/internal/deploy/assets/assets.go
  src/internal/deploy/cmds/cmds.go
  src/internal/serviceenv/config.go
  src/server/cmd/pachd/main.go
  src/server/pps/server/api_server.go
  src/server/pps/server/server.go
  src/server/pps/server/worker_rc.go
Labels: needs docs

#6420 Add pachctl inspect jobset/commitset
  src/internal/cmdutil/cobra.go
  src/internal/cmdutil/util.go
  src/internal/deploy/cmds/cmds.go
  src/server/cmd/pachctl/cmd/cmd.go
  src/server/config/cmds.go
  src/server/pachyderm_test.go
  src/server/pfs/cmds/cmds.go
  src/server/pfs/pretty/pretty.go
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
  src/server/spout_test.go
  src/server/transaction/cmds/cmds.go
Labels: 2.0.0

#6443 Add List JobSet RPC and pachctl command
  src/client/transaction.go
  src/internal/auth/interceptor.go
  src/internal/clientsdk/pps.go
  src/internal/testpachd/mock_pachd.go
  src/pps/pps.pb.go
  src/pps/pps.proto
  src/server/pps/cmds/cmds.go
  src/server/pps/pretty/pretty.go
  src/server/pps/server/api_server.go
Labels: 2.0.0

#6444 Add List CommitSet RPC and pachctl command
  src/client/transaction.go
  src/internal/auth/interceptor.go
  src/internal/clientsdk/pfs.go
  src/internal/testpachd/mock_pachd.go
  src/pfs/pfs.pb.go
  src/pfs/pfs.proto
  src/server/pfs/cmds/cmds.go
  src/server/pfs/pretty/pretty.go
  src/server/pfs/server/api_server.go
  src/server/pfs/server/driver.go
Labels: 2.0.0
