Repository pachyderm/pachyderm, pull requests merged in 2021-01, with the labels that each got.

#5566 Fix pachctl put file paths when run from windows
  src/server/pfs/cmds/cmds.go
Labels: bug

#5574 Require admin status to call ModifyAdmins
  src/server/auth/server/api_server.go
  src/server/auth/server/testing/admin_test.go
Labels: 1.12.1

#5572 Require users to be logged in to call secrets API
  src/client/pps.go
  src/server/pachyderm_test.go
  src/server/pps/server/api_server.go
Labels: 1.12.1

#5523 Allow pipeline creation with extant output repo.
  src/server/auth/cmds/cmds_test.go
  src/server/auth/server/testing/auth_test.go
  src/server/pkg/testutil/build_pipeline.go
  src/server/pps/cmds/cmds_test.go
  src/server/pps/server/api_server.go
Labels: 1.12.0

#5565 Remove ability to activate auth as users other than root
  etc/testing/test_tls.sh
  src/client/auth/auth.pb.go
  src/client/auth/auth.proto
  src/plugin/vault/etc/pach-auth.sh
  src/plugin/vault/etc/setup-vault.sh
  src/plugin/vault/vault_test.go
  src/server/admin/server/admin_test.go
  src/server/auth/cmds/cmds.go
  src/server/auth/cmds/cmds_test.go
  src/server/auth/server/api_server.go
  src/server/auth/server/testing/admin_test.go
  src/server/auth/server/testing/config_test.go
  src/server/pkg/testutil/auth.go
  src/server/pps/server/s3g_sidecar_test.go
Labels: 2.0.0

#5600 Reference counting for hashtrees in cache
  src/server/pfs/server/driver.go
  src/server/pkg/hashtree/cache.go
  src/server/pkg/hashtree/db.go
  src/server/pkg/hashtree/hashtree_test.go
  src/server/pkg/hashtree/interface.go
Labels: 1.12.1

#5611 Fix postgres deployment manifest on windows using incorrect path separators
  src/server/pkg/deploy/assets/postgres.go
Labels: 2.0.0, bug

#5609 Performance improvements for reading output repo metadata
  go.mod
  go.sum
  src/server/pfs/server/driver.go
  src/server/pfs/server/driver_unix.go
  src/server/pfs/server/driver_windows.go
  src/server/pkg/obj/cache_client.go
  src/server/pkg/testpachd/real_env.go
Labels: 1.12.1

#5613 [1.12] Spouts use PutFileClient
  src/server/worker/pipeline/common.go
Labels: 1.12.1

#5614 Commit and job info debug dump
  go.mod
  go.sum
  src/client/debug.go
  src/client/debug/debug.pb.go
  src/client/debug/debug.proto
  src/server/auth/server/testing/auth_test.go
  src/server/debug/cmds/cmds.go
  src/server/debug/server/server.go
  src/server/pachyderm_test.go
  src/server/pfs/cmds/cmds.go
  src/server/pfs/pretty/pretty.go
  src/server/pps/cmds/cmds.go
  src/server/pps/pretty/pretty.go
Labels: 1.12.1, 2.0.0

#5619 Commit and job info debug dump (1.12.x)
  go.mod
  go.sum
  src/client/debug.go
  src/client/debug/debug.pb.go
  src/client/debug/debug.proto
  src/server/auth/server/testing/auth_test.go
  src/server/debug/cmds/cmds.go
  src/server/debug/server/server.go
  src/server/pachyderm_test.go
  src/server/pfs/cmds/cmds.go
  src/server/pfs/pretty/pretty.go
  src/server/pps/cmds/cmds.go
  src/server/pps/pretty/pretty.go
Labels: 1.12.1

#5629 2.0 logging
  go.mod
  go.sum
  src/client/pps.go
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/client/transaction.go
  src/server/pachyderm_test.go
  src/server/pkg/lokiutil/lokiutil.go
  src/server/pkg/testpachd/mock_pachd.go
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
  src/server/worker/pipeline/transform/worker.go
Labels: 1.12.2, 2.0.0
