Repository pachyderm/pachyderm, pull requests merged in 2021-02, with the labels that each got.

#5438 Adds an enteprise check to loki logging.
  go.mod
  go.sum
  src/client/admin/admin.pb.go
  src/client/admin/v1_10/auth/auth.pb.go
  src/client/admin/v1_10/pfs/pfs.pb.go
  src/client/admin/v1_10/pps/pps.pb.go
  src/client/admin/v1_11/auth/auth.pb.go
  src/client/admin/v1_11/enterprise/enterprise.pb.go
  src/client/admin/v1_11/pfs/pfs.pb.go
  src/client/admin/v1_11/pps/pps.pb.go
  src/client/admin/v1_7/auth/auth.pb.go
  src/client/admin/v1_7/enterprise/enterprise.pb.go
  src/client/admin/v1_7/hashtree/hashtree.pb.go
  src/client/admin/v1_7/pfs/pfs.pb.go
  src/client/admin/v1_7/pps/pps.pb.go
  src/client/admin/v1_8/auth/auth.pb.go
  src/client/admin/v1_8/enterprise/enterprise.pb.go
  src/client/admin/v1_8/pfs/pfs.pb.go
  src/client/admin/v1_8/pps/pps.pb.go
  src/client/admin/v1_9/auth/auth.pb.go
  src/client/admin/v1_9/pfs/pfs.pb.go
  src/client/admin/v1_9/pps/pps.pb.go
  src/client/auth/auth.pb.go
  src/client/debug/debug.pb.go
  src/client/enterprise/enterprise.pb.go
  src/client/pfs/pfs.pb.go
  src/client/pkg/config/config.pb.go
  src/client/pkg/shard/shard.pb.go
  src/client/pkg/tracing/extended/extended_trace.pb.go
  src/client/pps.go
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/client/transaction/transaction.pb.go
  src/client/version/versionpb/version.pb.go
  src/server/pachyderm_test.go
  src/server/pkg/bloom/bloom.pb.go
  src/server/pkg/cache/groupcachepb/groupcache.pb.go
  src/server/pkg/deploy/deploy.pb.go
  src/server/pkg/hashtree/hashtree.pb.go
  src/server/pkg/lokiutil/lokiutil.go
  src/server/pkg/metrics/metrics.pb.go
  src/server/pkg/storage/chunk/chunk.pb.go
  src/server/pkg/storage/fileset/fileset.pb.go
  src/server/pkg/storage/fileset/index/index.pb.go
  src/server/pkg/work/work.pb.go
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
  src/server/worker/common/common.pb.go
  src/server/worker/pipeline/transform/transform.pb.go
  src/server/worker/server/service.pb.go
Labels: 1.12.2

#5654 DL progress bars for 1.12.x
  go.mod
  go.sum
  src/server/pfs/cmds/cmds.go
  src/server/pkg/progress/progress.go
  src/server/pkg/sync/sync.go
Labels: 1.12.2

#5661 Apply PPS master fix (#5541) to 1.12.x branch
  src/server/admin/server/api_server.go
  src/server/pps/server/api_server.go
  src/server/pps/server/master.go
  src/server/pps/server/monitor.go
  src/server/pps/server/pipeline_controller.go
  src/server/pps/server/poller.go
  src/server/pps/server/server.go
Labels: 1.12.2

#5690 Fix pollPipelines crash
  src/server/pkg/backoff/retry.go
  src/server/pkg/backoff/retry_test.go
  src/server/pps/server/monitor.go
  src/server/pps/server/poller.go
Labels: 1.12.3

#5684 Check if binaries already exist during worker init.
  etc/worker/init.go
Labels: 1.12.3, 2.0.0

#5701 Check if binaries already exist during worker init.
  etc/worker/init.go
Labels: 1.12.3

#5691 Support Pachyderm services with no port
  src/server/pps/server/worker_rc.go
Labels: 1.12.3

#5709 Fix error when email_verified is not set in OIDC
  src/server/auth/server/oidc.go
Labels: 1.12.3

#5647 fix path to Preview.app in one example
  doc/docs/1.12.x/getting_started/beginner_tutorial.md
Labels: bug, docs

#5713 Feature stats 1.12.x
  src/server/pkg/metrics/metrics.go
  src/server/pkg/metrics/metrics.pb.go
  src/server/pkg/metrics/metrics.proto
  src/server/pkg/metrics/segment.go
Labels: 1.12.3

#5698 Add pipeline metrics
  src/internal/metrics/metrics.go
  src/internal/metrics/metrics.pb.go
  src/internal/metrics/metrics.proto
  src/internal/metrics/segment.go
Labels: 1.12.3, 2.0.0

#5696 Fix GOPATH variable in Makefile when running on Windows
  Makefile
Labels: bug

#5724 Avoid metrics report deadlock.
  src/server/pkg/metrics/metrics.go
Labels: 1.12.4

#5723 Collect previous logs in debug dump (1.12.x)
  src/server/auth/server/testing/auth_test.go
  src/server/debug/server/server.go
  src/server/pachyderm_test.go
Labels: 1.12.4

#5744 Output repo get file improvements (1.12.x)
  src/server/pfs/server/driver.go
  src/server/pfs/server/driver_unix.go
  src/server/pfs/server/driver_windows.go
  src/server/pkg/hashtree/db.go
Labels: 1.12.4

#5752 Fix metrics group inputs (1.12.x)
  src/server/pkg/metrics/metrics.go
Labels: 1.12.4

#5754 Fix issue when downloading chunk hashtree (1.12.x)
  src/server/worker/pipeline/transform/worker.go
Labels: 1.12.4
