Repository pachyderm/pachyderm, pull requests merged in 2021-03, with the labels that each got.

#5769 Check Since != nil before checking fields on Since
  src/server/pps/server/api_server.go
Labels: 1.12.5

#5780 Deprecate Vault Plugin in 1.12.5
  doc/docs/1.12.x/contributing/supported-releases.md
  doc/docs/master/contributing/supported-releases.md
Labels: 1.12.5

#5812 Update ohmyglob to fixed version.
  go.mod
  go.sum
Labels: 1.12.5

#5782 fsck should fix ErrSubvenanceOfProvenance
  src/server/pfs/server/driver.go
  src/server/pfs/server/driver_fsck.go
  src/server/pfs/server/testing/server_test.go
Labels: 1.12.5

#5830 Make ListPipeline faster by looking up spec commits concurrently
  src/server/pps/server/api_server.go
Labels: 1.12.5

#5848 Add deprecation warnings
  CHANGELOG.md
  src/server/pkg/deploy/cmds/cmds.go
Labels: 1.13

#5871 Implement NoSkip in CreatePipelineRequest in 1.x
  etc/pipeline-build/python/Dockerfile
  etc/testing/travis_install.sh
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pachyderm_test.go
  src/server/pkg/deploy/cmds/cmds.go
  src/server/pkg/ppsutil/util.go
  src/server/pps/server/api_server.go
  src/server/worker/logs/logger.go
  src/server/worker/pipeline/transform/registry.go
  src/server/worker/pipeline/transform/worker.go
Labels: 1.13.0

#5849 [Doc] Add helm install option to local installation and deploy section of Doc - 1.13
  doc/docs/master/assets/images/DFD_Reset_K8s.png
  doc/docs/master/assets/images/Docker_Desktop_Enable_k8s.png
  doc/docs/master/contributing/supported-releases.md
  doc/docs/master/deploy-manage/deploy/helm_install.md
  doc/docs/master/deploy-manage/deploy/index.md
  doc/docs/master/getting_started/images/k8s_docker_desktop.png
  doc/docs/master/getting_started/index.md
  doc/docs/master/getting_started/local_installation.md
  doc/mkdocs-master.yml
Labels: 1.13.0

#5839 [Doc] Scaling limitation 1.13
  doc/docs/master/deploy-manage/deploy/deploy-pachyderm-ide.md
  doc/docs/master/enterprise/index.md
  doc/docs/master/how-tos/use-pachyderm-ide/index.md
  doc/docs/master/reference/scaling_limits.md
  doc/docs/master/troubleshooting/pipeline_troubleshooting.md
  doc/mkdocs-master.yml
Labels: 1.13.0

#5904 [Doc] Added the --version flag to helm install - Helm - 1.13
  doc/docs/master-1.13.x/deploy-manage/deploy/helm_install.md
  doc/docs/master/deploy-manage/deploy/helm_install.md
  doc/mkdocs-1.13.x.yml
Labels: 1.13.0, docs

#5905 [Doc] 1.13 limitation documentation continued - update from feed back
  doc/docs/master-1.13.x/enterprise/index.md
  doc/docs/master-1.13.x/how-tos/use-pachyderm-ide/index.md
  doc/docs/master-1.13.x/reference/scaling_limits.md
  doc/docs/master-1.13.x/troubleshooting/pipeline_troubleshooting.md
  doc/docs/master/enterprise/index.md
  doc/docs/master/how-tos/use-pachyderm-ide/index.md
  doc/docs/master/reference/scaling_limits.md
  doc/docs/master/troubleshooting/pipeline_troubleshooting.md
Labels: 1.13.0, docs

#5906 [Doc] backport from master - PR 5892
  doc/docs/master-1.13.x/reference/pipeline_spec.md
Labels: 1.13.0, docs

#5913 [Doc] 1.13 Autoscaling continued... Removed old autoscaling page -> after some re-writting, will be part …
  doc/docs/master-1.13.x/deploy-manage/manage/autoscaling.md
  doc/docs/master/deploy-manage/manage/autoscaling.md
  doc/mkdocs-1.13.x.yml
  doc/mkdocs-master.yml
Labels: 1.13.0, docs

#5914 [Doc] 1.13 release status update
  doc/docs/1.12.x/contributing/supported-releases.md
  doc/docs/master-1.13.x/contributing/supported-releases.md
  doc/docs/master/contributing/supported-releases.md
Labels: 1.13.0

#5915 [Doc] 1.13 reprocess_spec: renamed every_commit in every_job
  doc/docs/master-1.13.x/reference/pipeline_spec.md
  doc/docs/master/reference/pipeline_spec.md
Labels: 1.13.0, docs

#5903 Rename pipeline option NoSkip to ReprocessSpec
  src/client/pps.go
  src/internal/ppsutil/util.go
  src/pps/pps.pb.go
  src/pps/pps.proto
  src/server/pps/server/api_server.go
  src/server/worker/pipeline/transform/registry.go
Labels: 1.13.0

#5924 [Doc] gp3 for pv on AWS
  doc/docs/1.11.x/deploy-manage/deploy/amazon_web_services/aws-deploy-pachyderm.md
  doc/docs/1.11.x/deploy-manage/deploy/custom_object_stores.md
  doc/docs/1.12.x/deploy-manage/deploy/amazon_web_services/aws-deploy-pachyderm.md
  doc/docs/1.12.x/deploy-manage/deploy/custom_object_stores.md
  doc/docs/master-1.13.x/deploy-manage/deploy/amazon_web_services/aws-deploy-pachyderm.md
  doc/docs/master-1.13.x/deploy-manage/deploy/custom_object_stores.md
  doc/docs/master/deploy-manage/deploy/amazon_web_services/aws-deploy-pachyderm.md
  doc/docs/master/deploy-manage/deploy/custom_object_stores.md
Labels: 1.13.0, docs
