Repository pachyderm/pachyderm, pull requests merged in 2021-08, with the labels that each got.

#6586 [Doc] [ci-skip] Removal of datum merge
  doc/docs/master/assets/images/auth.png
  doc/docs/master/assets/images/auth_dash1.png
  doc/docs/master/assets/images/auth_dash2.png
  doc/docs/master/assets/images/auth_dash3.png
  doc/docs/master/assets/images/auth_dash4.png
  doc/docs/master/assets/images/auth_dash5.png
  doc/docs/master/assets/images/d_datum_processing_one_to_one.svg
  doc/docs/master/assets/images/d_datum_processing_one_to_one_overwrite.svg
  doc/docs/master/assets/images/dashboard.png
  doc/docs/master/assets/images/dashboard1.png
  doc/docs/master/assets/images/dashboard2.png
  doc/docs/master/assets/images/dashboard3.png
  doc/docs/master/assets/images/stats.png
  doc/docs/master/assets/images/stats1.png
  doc/docs/master/assets/images/stats2.png
  doc/docs/master/assets/images/stats3.png
  doc/docs/master/assets/images/stats4.png
  doc/docs/master/concepts/images/parallel_data_processing.png
  doc/docs/master/concepts/images/parallel_data_processing_following_commit.png
  doc/docs/master/concepts/pipeline-concepts/datum/cross-union.md
  doc/docs/master/concepts/pipeline-concepts/datum/datum-processing-states.md
  doc/docs/master/concepts/pipeline-concepts/datum/glob-pattern.md
  doc/docs/master/concepts/pipeline-concepts/datum/index.md
  doc/docs/master/concepts/pipeline-concepts/datum/relationship-between-datums.md
  doc/docs/master/concepts/pipeline-concepts/job.md
  doc/docs/master/deploy-manage/deploy/environment-variables.md
  doc/docs/master/deploy-manage/manage/data_management.md
  doc/docs/master/how-tos/basic-data-operations/removing_data_from_pachyderm.md
  doc/mkdocs-master.yml
Labels: 2.0.0, docs

#6647 Remove context from transaction context.
  src/client/pfs.go
  src/internal/collection/transaction.go
  src/internal/dbutil/tx.go
  src/internal/internal.go
  src/internal/metrics/metrics.go
  src/internal/ppsutil/util.go
  src/internal/storage/chunk/option.go
  src/internal/storage/fileset/metadata_store.go
  src/internal/storage/fileset/option.go
  src/internal/storage/fileset/postgres_store.go
  src/internal/storage/fileset/storage.go
  src/internal/testpachd/mock_transaction.go
  src/internal/testpachd/real_env.go
  src/internal/transactionenv/env.go
  src/internal/transactionenv/refresh.go
  src/internal/transactionenv/txncontext/context.go
  src/server/auth/iface.go
  src/server/auth/server/api_server.go
  src/server/auth/server/authorize_req.go
  src/server/auth/server/util.go
  src/server/auth/testing/auth.go
  src/server/pachyderm_test.go
  src/server/pfs/server/api_server.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/master.go
  src/server/pfs/server/trigger.go
  src/server/pps/iface.go
  src/server/pps/server/api_server.go
  src/server/pps/server/pipeline_controller.go
  src/server/transaction/server/driver.go
  src/transaction/transaction.pb.go
  src/transaction/transaction.proto
Labels: 2.0.0

#6702 Expose offset field in 'pachctl get file' in 1.13.x
  src/server/pfs/cmds/cmds.go
  src/server/pkg/progress/progress.go
Labels: 1.13.4

#6703 Prevent ListPipeline from holding an open query.
  src/server/pachyderm_test.go
  src/server/pps/server/api_server.go
Labels: 2.0.0

#6594 [Doc] [ci-skip] Doc from pzf - commitset/ jobset renaming
  doc/docs/master/concepts/advanced-concepts/deferred_processing.md
  doc/docs/master/concepts/advanced-concepts/globalID.md
  doc/docs/master/concepts/data-concepts/commit.md
  doc/docs/master/concepts/data-concepts/file.md
  doc/docs/master/concepts/data-concepts/history.md
  doc/docs/master/concepts/images/global_commit_after_putfile.png
  doc/docs/master/concepts/pipeline-concepts/job.md
  doc/docs/master/how-tos/pipeline-operations/monitor-job-progress.md
  doc/docs/master/troubleshooting/pipeline_troubleshooting.md
  doc/mkdocs-master.yml
  doc/netlify.toml
Labels: docs, 2.0.0

#6735 Store pipeline specs in postgres.
  etc/testing/circle/kube_debug.sh
  src/internal/collection/types.go
  src/internal/middleware/auth/handler.go
  src/internal/ppsdb/ppsdb.go
  src/internal/ppsutil/util.go
  src/internal/testpachd/mock_transaction.go
  src/internal/transactionenv/env.go
  src/internal/transactionenv/refresh.go
  src/internal/transactionenv/txncontext/context.go
  src/pps/util.go
  src/server/auth/server/testing/auth_test.go
  src/server/cmd/pachctl/shell/completions.go
  src/server/cmd/worker/main.go
  src/server/pachyderm_test.go
  src/server/pfs/server/driver.go
  src/server/pps/iface.go
  src/server/pps/pretty/pretty.go
  src/server/pps/server/api_server.go
  src/server/pps/server/master.go
  src/server/pps/server/monitor.go
  src/server/pps/server/parallelism_test.go
  src/server/pps/server/pipeline_controller.go
  src/server/pps/server/poller.go
  src/server/pps/server/s3g_sidecar.go
  src/server/transaction/server/driver.go
  src/server/worker/driver/driver.go
  src/server/worker/pipeline/transform/registry.go
  src/server/worker/pipeline/transform/transform_test.go
  src/server/worker/worker.go
  src/transaction/transaction.pb.go
  src/transaction/transaction.proto
Labels: 2.0.0
