Repository pachyderm/pachyderm, pull requests merged in 2021-04, with the labels that each got.

#5909 Add labels for RHODS
  Dockerfile.pachd
  etc/pachd/Dockerfile
  etc/pipeline-build/go/Dockerfile
  etc/pipeline-build/python/Dockerfile
  etc/worker/Dockerfile
  goreleaser/docker-build-pipelines.yml
  goreleaser/docker.yml
Labels: 1.13.0

#5923 Fix enterprise check loophole with update pipeline
  src/server/pps/server/api_server.go
Labels: 1.13.0

#5912 Define the Prometheus metrics port
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.json
  etc/testing/deploy-manifests/golden/amazon-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.json
  etc/testing/deploy-manifests/golden/custom-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/google-deploy-manifest.json
  etc/testing/deploy-manifests/golden/google-deploy-manifest.yaml
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.json
  etc/testing/deploy-manifests/golden/microsoft-deploy-manifest.yaml
  src/server/pkg/deploy/assets/assets.go
Labels: 1.13.0

#5922 Few changes that should improve put file performance for small files
  go.mod
  go.sum
  src/server/cmd/pachd/main.go
  src/server/pfs/cmds/cmds.go
  src/server/pfs/server/api_server.go
  src/server/pfs/server/api_server_v2.go
  src/server/pfs/server/driver.go
  src/server/pfs/server/driver_v2.go
  src/server/pfs/server/obj_block_api_server.go
  src/server/pfs/server/server.go
  src/server/pfs/server/testing.go
  src/server/pkg/testpachd/real_env.go
Labels: 1.13.0

#5935 Add status-only flag to list datum.
  src/client/pps.go
  src/client/pps/pps.pb.go
  src/client/pps/pps.proto
  src/server/pps/cmds/cmds.go
  src/server/pps/server/api_server.go
Labels: 1.13.0

#5918 [Doc] [skip-ci] Fixed error on major/minor/point release terminology in Migration and Update doc
  doc/docs/1.11.x/deploy-manage/manage/migrations.md
  doc/docs/1.11.x/deploy-manage/manage/upgrades.md
  doc/docs/1.11.x/deploy-manage/manage/upgrades_migrations.md
  doc/docs/1.12.x/deploy-manage/manage/migrations.md
  doc/docs/1.12.x/deploy-manage/manage/upgrades.md
  doc/docs/1.12.x/deploy-manage/manage/upgrades_migrations.md
  doc/docs/1.13.x/deploy-manage/manage/migrations.md
  doc/docs/1.13.x/deploy-manage/manage/upgrades.md
  doc/docs/master/deploy-manage/manage/migrations.md
  doc/docs/master/deploy-manage/manage/upgrades.md
  doc/docs/master/deploy-manage/manage/upgrades_migrations.md
  doc/mkdocs-1.12.x.yml
Labels: docs

#6005 Increases the maximum request body size in the s3 gateway.
  src/server/pfs/s3/master_test.go
  src/server/pfs/s3/s3.go
Labels: 1.13.1

#6008 Fix enterprise check for pipeline autoscaling
  src/server/enterprise/server/enterprise_test.go
  src/server/pps/server/api_server.go
Labels: 1.13.1
